import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Toastprovider from "./toastprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toastprovider />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
